# configuration.nix
{ config, pkgs, ... }:

{
  imports =
    [
      # This file will be generated by the NixOS installer later
      ./hardware-configuration.nix 
    ];

  # --- Enable Flakes ---
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # --- Bootloader & Kernel ---
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelPackages = pkgs.linuxPackages;
  
  # Use the default kernel instead of _latest to ensure ZFS compatibility
  boot.kernelPackages = pkgs.linuxPackages;

  # --- ZFS & Ephemeral Root ---
  boot.zfs.requestEncryptionCredentials = true;
  
  # Fix the evaluation warning from the 26.11 NixOS changes
  boot.zfs.forceImportRoot = false;

  # --- Keyboard Layout & Localization ---
  # Ensure German layout (without dead keys) during boot (LUKS prompt) and in TTYs
  console.keyMap = "de-latin1-nodeadkeys";

  # Ensure German layout (without dead keys) in X11 and Wayland sessions
  services.xserver.xkb = {
    layout = "de";
    variant = "nodeadkeys";
  };

  # --- ZFS & Ephemeral Root ---
  
  # --- ZFS Networking Fix ---
  networking.hostId = "8425e349"; # Randomly generated 8-character hex string

  # --- Impermanence Boot Fix ---
  fileSystems."/persist".neededForBoot = true;

  # --- ZFS Ephemeral Root Rollback (Systemd Stage 1) ---
  boot.initrd.systemd.services.rollback = {
    description = "Rollback ZFS datasets to a pristine state";
    wantedBy = [ "initrd.target" ];
    after = [ "zfs-import.target" ];
    before = [ "sysroot.mount" ];
    path = with pkgs; [ zfs ];
    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      zfs rollback -r rpool/local/root@blank
    '';
  };

  nixpkgs.config.allowUnfree = true;

  # --- Hardware Config: Intel & Nvidia ---
  hardware.cpu.intel.updateMicrocode = true;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # --- Minimal Base System Environment ---
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    zfs
    vim
  ];

  # --- User Configuration ---
  users.users.mainuser = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    # Passwords should be managed declaratively later (e.g., hashed string or sops-nix)
  };

  # --- Impermanence Configuration ---
  environment.persistence."/persist" = {
    hideMounts = true;
    
    directories = [
      "/var/log"
      "/var/lib/nixos"
      "/var/lib/systemd/coredump"
      "/etc/NetworkManager/system-connections"
    ];
    files = [
      "/etc/machine-id"
    ];

    users.mainuser = {
      directories = [
        "projects"
        "games"
        "Downloads"
        "Documents"
        ".ssh"
      ];
      files = [];
    };
  };

  system.stateVersion = "26.11";
}
