# configuration.nix
{ config, pkgs, ... }:

{
  imports =
    [
      # This file will be generated by the NixOS installer later
      ./hardware-configuration.nix 
    ];

  # --- Enable Flakes ---
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # --- Bootloader & Kernel ---
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = false;
    device = "nodev";
    zfsSupport = true;
    enableCryptodisk = true;
  };
  
  boot.loader.efi.canTouchEfiVariables = true;
  boot.supportedFilesystems = [ "zfs" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # --- ZFS & Ephemeral Root ---
  boot.zfs.requestEncryptionCredentials = true;
  
  boot.initrd.postDeviceCommands = pkgs.lib.mkAfter ''
    zfs rollback -r rpool/local/root@blank
  '';

  # --- Hardware Config: Intel & Nvidia ---
  hardware.cpu.intel.updateMicrocode = true;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # --- Minimal Base System Environment ---
  environment.systemPackages = with pkgs; [
    git
    wget
    curl
    zfs
    vim
  ];

  # --- User Configuration ---
  users.users.mainuser = {
    isNormalUser = true;
    extraGroups = [ "wheel" "networkmanager" ];
    # Passwords should be managed declaratively later (e.g., hashed string or sops-nix)
  };

  # --- Impermanence Configuration ---
  environment.persistence."/persist" = {
    hideMounts = true;
    
    directories = [
      "/var/log"
      "/var/lib/nixos"
      "/var/lib/systemd/coredump"
      "/etc/NetworkManager/system-connections"
    ];
    files = [
      "/etc/machine-id"
    ];

    users.mainuser = {
      directories = [
        "projects"
        "games"
        "Downloads"
        "Documents"
        ".ssh"
      ];
      files = [];
    };
  };

  system.stateVersion = "24.05";
}
